#!/usr/bin/env bash
# Godot Plugin Studio — environment setup
# Installs Godot 4.6.2 headless Linux build, extracts API XML reference,
# installs gdtoolkit (gdlint + gdformat), and sets up the test harness.
#
# Re-run safe: skips steps already complete.

set -euo pipefail

GODOT_VERSION="4.6.2-stable"
GODOT_NAME="Godot_v${GODOT_VERSION}_linux.x86_64"
GODOT_ZIP_URL="https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_linux.x86_64.zip"

INSTALL_DIR="$HOME/godot"
BIN_DIR="$HOME/.local/bin"
API_DIR="$HOME/godot-api-reference"
TEST_PROJECT_DIR="$HOME/godot-plugin-studio-harness"

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}Godot Plugin Studio — environment setup${NC}"
echo "Target: Godot ${GODOT_VERSION}"
echo

# 1. Check for required tools
for tool in wget unzip python3; do
    if ! command -v "$tool" &> /dev/null; then
        echo -e "${RED}Missing required tool: ${tool}${NC}"
        echo "Please install it (e.g., sudo apt install ${tool}) and re-run."
        exit 1
    fi
done

# 2. Install Godot binary
mkdir -p "$INSTALL_DIR" "$BIN_DIR"

if [ ! -f "$BIN_DIR/godot" ] || ! "$BIN_DIR/godot" --version 2>/dev/null | grep -q "$GODOT_VERSION"; then
    echo -e "${YELLOW}Installing Godot ${GODOT_VERSION}...${NC}"
    
    cd "$INSTALL_DIR"
    if [ ! -f "${GODOT_NAME}.zip" ]; then
        wget -q --show-progress "$GODOT_ZIP_URL" -O "${GODOT_NAME}.zip"
    fi
    
    unzip -o "${GODOT_NAME}.zip"
    chmod +x "${GODOT_NAME}"
    
    # Symlink to PATH
    ln -sf "$INSTALL_DIR/${GODOT_NAME}" "$BIN_DIR/godot"
    
    # Verify
    "$BIN_DIR/godot" --version
    echo -e "${GREEN}✓ Godot installed${NC}"
else
    echo -e "${GREEN}✓ Godot ${GODOT_VERSION} already installed${NC}"
fi

# Ensure PATH
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo -e "${YELLOW}Add to your shell profile: export PATH=\"$BIN_DIR:\$PATH\"${NC}"
    export PATH="$BIN_DIR:$PATH"
fi

# 3. Extract API XML
if [ ! -d "$API_DIR" ] || [ -z "$(ls -A "$API_DIR" 2>/dev/null)" ]; then
    echo -e "${YELLOW}Extracting Godot API XML reference...${NC}"
    mkdir -p "$API_DIR"
    
    # Doctool dumps XML class references — this is the studio's primary source of truth
    "$BIN_DIR/godot" --headless --doctool "$API_DIR" --no-docbase 2>/dev/null || {
        # Some Godot builds put the output in a 'classes' subdir
        echo "Trying alternate doctool flag..."
        "$BIN_DIR/godot" --headless --doctool "$API_DIR" 2>/dev/null || true
    }
    
    # Some versions output to a nested directory — flatten if needed
    if [ -d "$API_DIR/doc/classes" ]; then
        mv "$API_DIR/doc/classes/"*.xml "$API_DIR/" 2>/dev/null || true
        rm -rf "$API_DIR/doc"
    fi
    if [ -d "$API_DIR/classes" ]; then
        mv "$API_DIR/classes/"*.xml "$API_DIR/" 2>/dev/null || true
        rm -rf "$API_DIR/classes"
    fi
    
    XML_COUNT=$(ls -1 "$API_DIR"/*.xml 2>/dev/null | wc -l)
    if [ "$XML_COUNT" -lt 100 ]; then
        echo -e "${RED}WARNING: API extraction produced only $XML_COUNT XML files (expected >1000)${NC}"
        echo "The Honesty Auditor will be impaired. Please check the doctool output manually."
    else
        echo -e "${GREEN}✓ API XML extracted ($XML_COUNT classes) to $API_DIR${NC}"
    fi
else
    XML_COUNT=$(ls -1 "$API_DIR"/*.xml 2>/dev/null | wc -l)
    echo -e "${GREEN}✓ API XML already extracted ($XML_COUNT classes at $API_DIR)${NC}"
fi

# 4. Install gdtoolkit (gdlint + gdformat)
if ! command -v gdlint &> /dev/null; then
    echo -e "${YELLOW}Installing gdtoolkit (gdlint, gdformat)...${NC}"
    
    if command -v pipx &> /dev/null; then
        pipx install gdtoolkit==4.* || pipx install gdtoolkit
    else
        echo "pipx not found; falling back to pip --user"
        python3 -m pip install --user gdtoolkit
        
        # Add user bin to PATH if needed
        USER_BIN="$HOME/.local/bin"
        if [[ ":$PATH:" != *":$USER_BIN:"* ]]; then
            echo -e "${YELLOW}Add to your shell profile: export PATH=\"$USER_BIN:\$PATH\"${NC}"
            export PATH="$USER_BIN:$PATH"
        fi
    fi
    
    if command -v gdlint &> /dev/null; then
        gdlint --version
        echo -e "${GREEN}✓ gdtoolkit installed${NC}"
    else
        echo -e "${RED}gdtoolkit install failed; static analysis will not work${NC}"
    fi
else
    echo -e "${GREEN}✓ gdtoolkit already installed ($(gdlint --version 2>&1 | head -1))${NC}"
fi

# 5. Test harness project
if [ ! -d "$TEST_PROJECT_DIR" ]; then
    echo -e "${YELLOW}Creating test harness project at $TEST_PROJECT_DIR...${NC}"
    mkdir -p "$TEST_PROJECT_DIR/addons"
    
    cat > "$TEST_PROJECT_DIR/project.godot" << 'EOF'
; Godot Plugin Studio — Test Harness Project
; Generated by setup-godot.sh; do not edit manually.

config_version=5

[application]
config/name="Godot Plugin Studio Harness"
config/features=PackedStringArray("4.6", "Forward Plus")

[rendering]
renderer/rendering_method="forward_plus"
EOF
    
    echo -e "${GREEN}✓ Test harness created${NC}"
else
    echo -e "${GREEN}✓ Test harness exists at $TEST_PROJECT_DIR${NC}"
fi

# 6. Verification summary
echo
echo -e "${GREEN}=== Setup verification ===${NC}"
echo -n "godot:    "; "$BIN_DIR/godot" --version 2>/dev/null || echo "FAILED"
echo -n "gdlint:   "; (gdlint --version 2>&1 | head -1) || echo "FAILED"
echo -n "gdformat: "; (gdformat --version 2>&1 | head -1) || echo "FAILED"
echo -n "API XML:  "; ls -1 "$API_DIR"/*.xml 2>/dev/null | wc -l
echo

# 7. Smoke test: try a parse check
echo -e "${YELLOW}Running smoke test...${NC}"
TEST_FILE=$(mktemp /tmp/gps-smoke-XXXXXX.gd)
cat > "$TEST_FILE" << 'EOF'
@tool
extends EditorPlugin

func _enter_tree() -> void:
    var arr: Array[Node] = []
    var dict: Dictionary[String, int] = {}
    pass

func _exit_tree() -> void:
    pass
EOF

SMOKE_OUT=$("$BIN_DIR/godot" --headless --script "$TEST_FILE" --check-only 2>&1)
if echo "$SMOKE_OUT" | grep -qE "Parse Error|SCRIPT ERROR|Failed to load"; then
    echo -e "${RED}✗ Smoke test FAILED — parse check produced errors${NC}"
    echo "$SMOKE_OUT"
    rm -f "$TEST_FILE"
    exit 1
else
    echo -e "${GREEN}✓ Smoke test passed${NC}"
    rm -f "$TEST_FILE"
fi

# 8. API verification spot-check
echo -e "${YELLOW}Spot-checking API XML integrity...${NC}"
EXPECTED_CLASSES=("EditorPlugin" "EditorInspectorPlugin" "EditorInterface" "Node" "EditorUndoRedoManager")
for cls in "${EXPECTED_CLASSES[@]}"; do
    if [ -f "$API_DIR/$cls.xml" ]; then
        echo -e "  ${GREEN}✓${NC} $cls.xml found"
    else
        echo -e "  ${RED}✗${NC} $cls.xml MISSING — Honesty Auditor will be impaired"
    fi
done

echo
echo -e "${GREEN}=== Studio environment ready ===${NC}"
echo "You can now run plugin development tickets through this skill."
echo
echo "Quick commands:"
echo "  godot --version                          — verify Godot install"
echo "  godot --headless --script <file.gd> --check-only  — parse-check a script"
echo "  gdlint <file.gd>                         — static analysis"
echo "  grep 'method name=\"X\"' \$HOME/godot-api-reference/<Class>.xml  — verify API"
echo
echo "Test harness project: $TEST_PROJECT_DIR"
echo "API XML reference:    $API_DIR"
